repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: 
          - -S

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args:
          - --max-line-length=88
          - --select=F401,E501,F841,F811
          - --per-file-ignores=__init__.py:F401
